This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main.acn....done (12 entries accepted, 0 rejected).
Sorting entries....done (49 comparisons).
Generating output file main.acr....done (31 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
